TASKMANAGER_MAX_THREADS = 20
# unknown task
TASK_EXECUTION_NONE = 0
# execute task immediately
TASK_EXECUTION_EXECUTE_MODE = 1
# batch task
TASK_EXECUTION_BATCH_MODE = 2

# Task status
TASK_STATUS_QUEUE = 0
TASK_STATUS_SUCCESS = 100
TASK_STATUS_ERROR = 200

# Task priority
TASK_PRIORITY_DEFAULT = 0
TASK_PRIORITY_HIGH = 1

# Task limit settings
TASK_LIMIT_TYPE_NONE = 0
TASK_LIMIT_TYPE_HOUR = 1
TASK_LIMIT_TYPE_DAY = 2

# Task retry settings
SHOULD_RETRY_CLOSE = 0
SHOULD_RETRY_OPEN = 1
