# crawler request timeout (s)
REQUEST_TIME_OUT = 10  # 访问超时时间设置10s
# downloader codec type
DOWNLOADER_CODEC_VIDEO_TYPE = 1
DOWNLOADER_CODEC_AUDIO_TYPE = 2
DOWNLOADER_CODEC_MUXER_TYPE = 3

# error code for successful
GLOBAL_SUCC = 0
# global error code 1000-1099
GLOBAL_ERR_UNKNOWN = 1000
GLOBAL_ERR_PARAMETER_EMPTY = 1001
GLOBAL_ERR_PATH_NOT_FOUND = 1002
GLOBAL_ERR_YT_DLP_NOT_INSTALLED = 1003
# task module
TASK_ERR_UNKNOWN = 1100
TASK_ERR_CHECK_URL = 1101
# config module
