# crawler request timeout (s)
REQUEST_TIME_OUT = 10  # 访问超时时间设置10s
# downloader codec type
DOWNLOADER_CODEC_VIDEO_TYPE = 1
DOWNLOADER_CODEC_AUDIO_TYPE = 2
DOWNLOADER_CODEC_MUXER_TYPE = 3
# 配置部分
# 音频转文字
# 不提取
TASK_CONFIG_ASR_FROM_NONE = 0
# 从字幕提取
TASK_CONFIG_ASR_FROM_SUBTITLE = 1
# 本地 whisper
TASK_CONFIG_ASR_FROM_FASTER_WHISPER = 2
# 腾讯云ASR
TASK_CONFIG_ASR_FROM_TENCENT_CLOUD = 3
# 讯飞云ASR
TASK_CONFIG_ASR_FROM_XF_YUN = 4
# 本地 whisper 配置
TASK_CONFIG_ASR_MLX_WHISPER = 1
TASK_CONFIG_ASR_FASTER_WHISPER = 2
TASK_CONFIG_ASR_OPENAI_WHISPER = 3
# tts engine server list
TTS_LIST_AZURE_TTS_V1 = 1
TTS_LIST_AZURE_TTS_V2 = 2
TTS_LIST_SILICON_FLOW_TTS = 3
TTS_LIST_GOOGLE_GEMINI_TTS = 4
TTS_LIST_XIAOMI_MIMO_TTS = 5
# tts voice preview
TTS_CONFIG_PREVIEW = {
    "zh": "你好，这是一段试听音频",
    "en": "Hello, this is a sample audio file"
}
# proxy server type
PROXY_CONFIG_TYPE_UNKNOWN = 0
PROXY_CONFIG_TYPE_HTTPS = 1
PROXY_CONFIG_TYPE_SOCKS5 = 2

# error code for successful
GLOBAL_SUCC = 0
# global error code 1000-1099
GLOBAL_ERR_UNKNOWN = 1000
GLOBAL_ERR_PARAMETER_EMPTY = 1001
GLOBAL_ERR_PATH_NOT_FOUND = 1002
GLOBAL_ERR_YT_DLP_NOT_INSTALLED = 1003
# task module
TASK_ERR_UNKNOWN = 1100
TASK_ERR_CHECK_URL = 1101
TASK_CONFIG_ERR_CONFIG_FILE = 1110
# config module
TTS_CONFIG_ERR_UNKNOWN = 1200
TTS_CONFIG_ERR_ENGINE_NOT_FOUND = 1201
TTS_CONFIG_ERR_VOICE_NOT_FOUND = 1202
TTS_CONFIG_ERR_VOICE_TEXT_NOT_FOUND = 1203
TTS_CONFIG_ERR_PREVIEW_FILE_EMPTY = 1204
TTS_CONFIG_ERR_PREVIEW_FILE_NOT_EXISTS = 1205
